alias d='docker'
alias dlogs='docker logs $1'
alias datt='docker attach'
alias db='docker build .'
alias dc='docker-compose '
alias dcb='docker-compose build'
alias dcc='docker-compose config'
alias dcd='docker-compose down'
alias dci='docker-compose images'
alias dclimg='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
alias dclogs='docker-compose logs'
alias dcu='docker-compose up'
alias ddiff='docker diff'
alias dex="docker exec -it $1 /bin/bash"
alias dgcdr='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e DRY_RUN=1 spotify/docker-gc'
alias dgcex='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e DRY_RUN=0 spotify/docker-gc'
alias di='docker images'
alias dk='docker kill  '
alias dps='docker ps'
alias dpsa='docker ps -a'
alias drestartf='docker start $(docker ps -ql) && docker attach $(docker ps -ql)'
alias drmc='docker rm '
alias drmi='docker image rm '
alias drn='docker rmi -f $(docker images -a | grep "<none>" | awk {"print $3"})'
alias drun='$winpty docker run -ti'